# EX 2

In [2]:
import numpy as np

#2) Create a list of size 10 with all zeros

x = np.zeros(10)
print(x)

#3) Assume you are working on Jupyter Notebook
#  How to you get documentation of numpy multiply fuction?

#np.multiply?

#help(np.multiply)



#Create a 3 X 3 Matrix with values ranging from 0 to 8
y = np.arange(9).reshape(3, 3)
print(y)

#5) Create a 3 X 3 X 3 array with random values 

z = np.random.random ((3,3,3))
print(z)

#6) Create a 5 X 5 array with random values.  Find the minimum and maximum values.

z = np.random.random((5,5))
print(z)
print(z.min())
print(z.max())

#7) Create an array of 10 random values.  Rearrange the arrange in order.

x = np.random.random((10))
print(x)
x =  np.sort(x)
print(x)

#8) Create an array of 10 random values.  Get the sum and average value of the elements.

x = np.random.random((10))
print(x)
print(np.sum(x))
print(np.average(x))


print(z.shape)

print(z.shape[0])


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[0.25118762 0.00906307 0.8847956 ]
  [0.95601462 0.80308166 0.32637576]
  [0.80806023 0.18829241 0.94619454]]

 [[0.44010701 0.6365804  0.40703001]
  [0.68930036 0.7192429  0.22029274]
  [0.82147004 0.61637045 0.8114675 ]]

 [[0.34816244 0.08717666 0.06449589]
  [0.58532104 0.49609691 0.3082024 ]
  [0.45391671 0.97283775 0.71625051]]]
[[0.20508501 0.38685494 0.25436271 0.15768764 0.35299941]
 [0.82465439 0.84413719 0.93722657 0.9043482  0.9237994 ]
 [0.07997655 0.44882706 0.00880964 0.51474442 0.95888381]
 [0.83801468 0.207232   0.47055229 0.07264442 0.18780735]
 [0.40906453 0.93473309 0.67749208 0.52466349 0.13297242]]
0.00880963946586688
0.9588838147618634
[0.49514153 0.42559517 0.94330602 0.88849414 0.08471375 0.36291299
 0.28658701 0.54432318 0.06495057 0.68152154]
[0.06495057 0.08471375 0.28658701 0.36291299 0.42559517 0.49514153
 0.54432318 0.68152154 0.88849414 0.94330602]
[0.8378087  0.11778839 0.54845187 0.19584178 

# BASICS

In [3]:
# Numpy array is a grid of values, values are indexed via a set of nonnegative integers.  
# Numpy arrays can be initiated from nested Python list.
# Need to import numpy library
# rank is the number of dimensions in the array

import numpy as np

x = np.array ([10,20,30])

print(type(x))

print(x.shape)  # size of the numpy array

print(x[0], x[1])  # accessing array elements with indexis

x[0] = 40 # changing array element

print(x) 

y = np.array([[10,20,30], [40,50,60]])  # create an array of rank 2

print(y.shape)  # returns number of elements in the array

print (y[0,0], y[0,1], y[1,2])

x = np.zeros((2,2)) #create an array of zeros
print(x)

y = np.ones((1,2))  # create an array of ones
print(y)

z = np.full((2,2), 7) # Return a array filled with the value 7
print(z)

a = np.eye(3) # create an identify matrix, 3X3
print(a)

b = np.random.random((2,2)) # create an array of random values
print(b)

myarray = np.array([10,20,30,40], ndmin=2) #ndmin =2, minimum dimensions is 2
print(myarray)

x,y = np.loadtxt('data.txt', skiprows=1, unpack=True) #load dataset from text file,
                                                    # skip the first row,
                                                    # unpack = True retuns the columns as separate arrays
    

print(x)
print(y)

array2 = np.genfromtxt('data2.txt', skip_header=1,filling_values =-999) #missing value will be -999
print(array2)

# refer to the doc https://numpy.org/devdocs/user/basics.io.genfromtxt.html#filling-values


array1 = np.arange(start=0.1, stop=7.4, step=2.5) # create an array with starting value, increment value (step), and stop before value 10 is reached
print(array1)

# save data in text file
np.savetxt('out_data.txt', array1, delimiter=',')


a = np.ones ((2,3))
print(a)

b = np.random.random((2,3))
print(b)

print(a+b)

print(a-b)

print(a*b)

print(a/b)


x = np.array ([[0,1,2], [3,4,5]])
print(x)
print(x[1])  # all elements of index 1 (row 1)
print(x[0][2])  # element at row 0, column 0
print(x[0:2,1]) # element at row 0 and 1 (2-1), column 1
print(np.transpose(x))  # transposing the array, which means switch around the array shape



<class 'numpy.ndarray'>
(3,)
10 20
[40 20 30]
(2, 3)
10 20 60
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.77829783 0.56293903]
 [0.71743535 0.09987966]]
[[10 20 30 40]]
[100. 200. 300. 400.]
[200. 300. 400. 500.]
[[ 100.  200.]
 [ 200. -999.]
 [ 300.  400.]
 [ 400.  500.]]
[0.1 2.6 5.1]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.95123988 0.50358647 0.69996469]
 [0.36605938 0.19181456 0.01918908]]
[[1.95123988 1.50358647 1.69996469]
 [1.36605938 1.19181456 1.01918908]]
[[0.04876012 0.49641353 0.30003531]
 [0.63394062 0.80818544 0.98081092]]
[[0.95123988 0.50358647 0.69996469]
 [0.36605938 0.19181456 0.01918908]]
[[ 1.05125954  1.9857563   1.42864349]
 [ 2.73179725  5.2133687  52.11296959]]
[[0 1 2]
 [3 4 5]]
[3 4 5]
2
[1 4]
[[0 3]
 [1 4]
 [2 5]]
